[package]
name = "short-ans"
version = "0.1.0"
authors = ["Bob Forsman <bob.forsman@ericsson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
symbol-table = { path = "../symbol-table" }
